spring.application.name=spring-boot-vault-sample
server.port=8080

# H2 Database (Secrets from Vault)
spring.datasource.url=jdbc:h2:mem:vaultdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${db.username:sa}
spring.datasource.password=${db.password:}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Custom Secrets
app.api-key=${api.key:default-key}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Vault (override token/secret via env vars or --args at runtime)
spring.cloud.vault.uri=https://vault.persis.or.id:8270
spring.cloud.vault.scheme=https
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN:}
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=persislabs-dev
spring.cloud.vault.kv.default-context=testing
spring.cloud.vault.fail-fast=false
spring.config.import=optional:vault://

# Logging
logging.level.org.springframework.vault=INFO
logging.level.id.my.persislabs.vault=DEBUG
